spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  redis:
    host: session-redis
    port: 6379
  session:
    store-type: redis
server:
  servlet:
    session:
      timeout: 30
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session
logging.level.com.sam: DEBUG
