apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: zcp-demo
  labels:
    app: springboot
spec:
  ports:
  - port: 8080
    nodePort: 32000
  selector:
    app: springboot
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-redis
  namespace: zcp-demo
  labels:
    app: springboot
spec:
    replicas: 1
    selector:
      matchLabels:
        app: springboot
    template:
      metadata:
        labels:
          app: springboot
      spec:
        containers:
        - name: sam-springboot-redis
          image: myguddy/sam-springboot-redis
          ports:
          - containerPort: 8080