apiVersion: v1
kind: Service
metadata:
  name: session-redis
  namespace: zcp-demo
  labels:
    backng: redis
spec:
  ports: 
  - port: 6379
  selector:
    backing: redis
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: zcp-demo
spec:
  selector:
    matchLabels:
      backing: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        backing: redis
    spec:
        containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6379